export const projects = [
    {
      image: "/Great-stock-pro-image-show3.png",
      tags: ["React.js", "TypeScript", "Node.js", "MongoDB"],
      github: "https://github.com/rodrigojmayer/stockpro",
      demo: 'https://stockpro-deploy.onrender.com/',
      slug: 'stockpro',
      videos: [
        { src: '01-Main-page',
          title: { es: 'Página principal sin inicio de sesión', en: 'Main page unlogged' },
        },
        { src: '02-Sign-up',
          title: { es: 'Página de registro', en: 'Sign up' },
        },
        { src: '03-Log-in-with-user-pass',
          title: { es: 'Iniciar sesión con usuario y contraseña', en: 'Log in with user and password' },
        },
        { src: '04-Log-in-with-gmail',
          title: { es: 'Registro automático e inicio de sesión con Gmail', en: 'Automatic registration and login with Gmail' },
        },
        { src: '05-Create-stock',
          title: { es: 'Crear nuevo stock', en: 'Create new stock' },
        },
        { src: '06-Update-amount',
          title: { es: 'Actualizar cantidad', en: 'Update amount' },
        },
        { src: '07-Edit-stock',
          title: { es: 'Editar stock', en: 'Edit stock' },
        },
        { src: '08-Delete-stock',
          title: { es: 'Eliminar stock', en: 'Delete stock' },
        },
        { src: '09-Massive-update-amount',
          title: { es: 'Actualización masiva de cantidad', en: 'Massive update amount' },
        },
        { src: '10-Alert-by-amount',
          title: { es: 'Alerta por cantidad', en: 'Alert by amount' },
        },
        { src: '11-Alert-by-date',
          title: { es: 'Alerta por fecha', en: 'Alert by date' },
        },
        { src: '12-Alerts-on-top',
          title: { es: 'Alertas en la parte superior', en: 'Alerts on top' },
        },
        { src: '13-Manage-columns',
          title: { es: 'Administrar columnas', en: 'Manage columns' },
        },
        { src: '14-Custom-fields',
          title: { es: 'Campos personalizados', en: 'Custom fields' },
        },
        { src: '15-Order-stock',
          title: { es: 'Ordenar stock', en: 'Order stock' },
        },
        { src: '16-Global-search',
          title: { es: 'Búsqueda global', en: 'Global search' },
        },
        { src: '17-Filter-by-field',
          title: { es: 'Filtrar por campos', en: 'Filter by fields' },
        },
        { src: '18-Profile',
          title: { es: 'Perfil', en: 'Profile' },
        },
        { src: '19-Preferences-language',
          title: { es: 'Lenguajes', en: 'Languages' },
        },
        { src: '20-Preferences-color-mode',
          title: { es: 'Tema visual', en: 'Color mode' },
        },
        { src: '21-Users',
          title: { es: 'Usuarios', en: 'Users' },
        },
        { src: '22-Forgot-password',
          title: { es: 'Olvidé mi contraseña', en: 'Forgot password' },
        },
      ],
    },
    {
      image: "/Great-expensecontrolheroimage.png",
      tags: ["React.js", "TypeScript", "Node.js", "CSS"],
      github: "https://github.com/rodrigojmayer/expense_control_frontend",
      demo: "https://expense-control-frontend.onrender.com/",
      slug: 'expensecontrol',
      videos: [
        { src: '01-Start-page',
          title: { es: 'Pagina de inicio', en: 'Start page' },
        },
        { src: '02-Payment-method-page',
          title: { es: 'Método de pago', en: 'Payment method' },
        },
        { src: '03-Articles-page',
          title: { es: 'Página de artículos', en: 'Articles page' },
        },
        { src: '04-Create-new-article',
          title: { es: 'Crear nuevo artículo', en: 'Create new article' },
        },
        { src: '05-Create-new-group',
          title: { es: 'Crear nuevo grupo', en: 'Create new group' },
        },
        { src: '06-Edit-article',
          title: { es: 'Editar artículo', en: 'Edit article' },
        },
        { src: '07-Delete-article',
          title: { es: 'Eliminar artículo', en: 'Delete article' },
        },
        { src: '08-Edit-group',
          title: { es: 'Editar grupo', en: 'Edit group' },
        },
        { src: '09-Delete-group',
          title: { es: 'Eliminar grupo', en: 'Delete group' },
        },
        { src: '10-Select-articles',
          title: { es: 'Seleccionar artículos', en: 'Select articles' },
        },
        { src: '11-Cart-page',
          title: { es: 'Vista previa del carrito', en: 'Cart preview page' },
        },
        { src: '12-Export-transaction',
          title: { es: 'Exportar transacción', en: 'Export transaction' },
        }
      ],
    },
    {
      image: "/networkimage12.png",
      tags: ["Python", "Django", "Java Script"],
      github: "https://github.com/rodrigojmayer/RJMNetwork",
      demo: "https://rjmnetwork.onrender.com/",
      slug: 'network',
      videos: [
        { src: '01-Main_page_unlogged',
          title: { es: 'Página principal sin inicio de sesión', en: 'Sign up page'},
        },  
        { src: '02-Sign_up',        
          title: { es: 'Página de registro', en: 'Main page logged' },
        },
        { src: '03-Main_page_logged',  
          title: { es: 'Página principal iniciada sesión', en: 'Main page logged' },
        },
        { src: '04-Create_new_post',   
          title: { es: 'Crear nueva publicación', en: 'Create new post' },
        },
        { src: '05-Profile_logged',    
          title: { es: 'Página de perfil del usuario', en: 'User profile page' },
        },
        { src: '06-Edit_profile',      
          title: { es: 'Editar perfil registrado', en: 'Edit profile logged' },
        },
        { src: '07-Edit_post',         
          title: { es: 'Editar publicación', en: 'Edit post' },
        },
        { src: '08-Users_difference',  
          title: { es: 'Diferenciar usuarios', en: 'Users difference' },
        },
        { src: '09-Login_page',      
          title: { es: 'Página inicio sesion', en: 'Login page' },
        },
        { src: '10-Followed_users',  
          title: { es: 'Usuarios seguidos', en: 'Followed Users' },
        },
        { src: '11-Liked_posts',  
          title: { es: 'Publicaciones que han gustado', en: 'Liked posts' },
        },
        { src: '12-Search',    
          title: { es: 'Búsqueda', en: 'Search' },
        },
        { src: '13-Tablet',   
          title: { es: 'Despliegue responsivo en tableta', en: 'Tablet responsive' },
        },
        { src: '14-Mobile',    
          title: { es: 'Despliegue responsivo en móvil', en: 'Mobile responsive' },
        },
      ],
    },
    {
      image: "/auctionsimage3.jpg",
      imagePositionValues: "center 27%",
      tags: ["Python", "Django", "HTML", "JavaScript", "CSS", "SCSS", "PowerShell"],
      github: "https://github.com/rodrigojmayer/AuctionsProject",
      demo: "https://rjmauctions.onrender.com",
      slug: 'auctions',
      videos: [
        { src: '01-Active_listings_without_log_in',
          title: { es: 'Listado de articulos sin iniciar sesión', en: 'Auctions listing without log in'},
        },  
        { src: '02-Article_without_log_in',        
          title: { es: 'Acceso a los artículos sin iniciar sesión', en: 'Access to articles without log in' },
        },
        { src: '03-Register',        
          title: { es: 'Registro', en: 'Register' },
        },
        { src: '04-Article_bike_logged_in_bigger_image',        
          title: { es: 'Acceso al artículo', en: 'Access to article' },
        },
        { src: '05-Make_question',        
          title: { es: 'Hacer preguntas', en: 'Make questions' },
        },
        { src: '06-Place_bid',        
          title: { es: 'Hacer oferta', en: 'Place bid' },
        },
        { src: '07-Add_to_watch_list',        
          title: { es: 'Añadir a lista de seguimiento', en: 'Add to watch list' },
        },
        { src: '08-Categories',        
          title: { es: 'Categorías', en: 'Categories' },
        },
        { src: '09-Post_item',        
          title: { es: 'Publicar elemento', en: 'Post item' },
        },
        { src: '10-Log_in_user_owner_of_auction',        
          title: { es: 'Iniciar sesión usuario propietario de la subasta', en: 'Log in user owner of auction' },
        },
        { src: '11-Answer_question',        
          title: { es: 'Responder pregunta', en: 'Answer question' },
        },
        { src: '12-Close_auction',        
          title: { es: 'Cerrar subasta', en: 'Close auction' },
        },
        { src: '13-Log_in_auction_winner',        
          title: { es: 'Iniciar sesión ganador de la subasta', en: 'Log in auction winner' },
        },
        { src: '14-Ipad_responsive',        
          title: { es: 'Despliegue responsivo en tableta', en: 'Tablet responsive' },
        },
        { src: '15-Mobile_responsive',        
          title: { es: 'Despliegue responsivo en móvil', en: 'Mobile responsive' },
        },
      ],
    },
    {
      image: "/social-media-app-feed.jpg",
      tags: ["Next.js", "Supabase", "Tailwind", "Vercel"],
      github: "#",
      demo: "#",
      slug: 'mail',
      videos: [
        { src: '01-Sign_up_page',
          title: { es: 'Página de registro', en: 'Sign up page'},
        }, 
        { src: '02-Basic_login_page',
          title: { es: 'Página de inicio de sesión', en: 'Basic login page'},
        }, 
        { src: '03-Inbox',
          title: { es: 'Bandeja de entrada', en: 'Inbox'},
        }, 
        { src: '04-Search',
          title: { es: 'Búsqueda', en: 'Search'},
        }, 
        { src: '05-Archived',
          title: { es: 'Archivado', en: 'Archived'},
        }, 
        { src: '06-Compose',
          title: { es: 'Componer', en: 'Compose'},
        }, 
        { src: '07-Email_view',
          title: { es: 'Vista de correo electrónico', en: 'Email view'},
        }, 
        { src: '08-Email_replay',
          title: { es: 'Respuesta de correo electrónico', en: 'Email reply'},
        }, 
        { src: '09-Sent_emails',
          title: { es: 'Correos electrónicos enviados', en: 'Sent emails'},
        }, 
        { src: '10-Sent_email',
          title: { es: 'Email enviado', en: 'Sent email'},
        }, 
        { src: '11-Tablet_responsive',
          title: { es: 'Despliegue responsivo en tableta', en: 'Tablet responsive'},
        }, 
        { src: '12-Mobile_responsive',
          title: { es: 'Despliegue responsivo en móvil', en: 'Mobile responsive'},
        }, 
      ], 
    },
  ]