export const projects = [
    {
      image: "/Great-stock-pro-image-show3.png",
      tags: ["React.js", "TypeScript", "Node.js", "MongoDB"],
      // tags: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
      github: "https://github.com/rodrigojmayer/stockpro",
      demo: 'https://stockpro-deploy.onrender.com/',
      video: '/StockPro/01-Main-page.webm',
      videos: [
        '/StockPro/01-Main-page.webm',
        '/StockPro/02-Sign-up.webm',
        '/StockPro/03-Log-in-with-user-pass.webm',
        '/StockPro/04-Log-in-with-gmail.webm',
        '/StockPro/05-Create-stock.webm',
        '/StockPro/06-Update-amount.webm',
        '/StockPro/07-Edit-stock.webm',
        '/StockPro/08-Delete-stock.webm',
        '/StockPro/09-Massive-update-amount.webm',
        '/StockPro/10-Alert-by-amount.webm',
        '/StockPro/11-Alert-by-date.webm',
        '/StockPro/12-Alerts-on-top.webm',
        '/StockPro/13-Manage-columns.webm',
        '/StockPro/14-Custom-fields.webm',
        '/StockPro/15-Order-stock.webm',
        '/StockPro/16-Global-search.webm',
        '/StockPro/17-Filter-by-field.webm',
        '/StockPro/18-Profile.webm',
        '/StockPro/19-Preferences-language.webm',
        '/StockPro/20-Preferences-color-mode.webm',
        '/StockPro/21-Users.webm',
        '/StockPro/22-Forgot-password.webm',
      ],
      slug: 'stockpro',
    },
    {
      image: "/Great-expensecontrolheroimage.png",
      tags: ["React.js", "TypeScript", "Node.js", "CSS"],
      github: "https://github.com/rodrigojmayer/expense_control_frontend",
      demo: "https://expense-control-frontend.onrender.com/",
      video: '/ExpenseControl/01-Start-page.webm',
      videos: [
        '/ExpenseControl/01-Start-page.webm',
        '/ExpenseControl/02-Payment-method-page.webm',
        '/ExpenseControl/03-Articles-page.webm',
        '/ExpenseControl/04-Create-new-article.webm',
        '/ExpenseControl/05-Create-new-group.webm',
        '/ExpenseControl/06-Edit-article.webm',
        '/ExpenseControl/07-Delete-article.webm',
        '/ExpenseControl/08-Edit-group.webm',
        '/ExpenseControl/09-Delete-group.webm',
        '/ExpenseControl/10-Select-articles.webm',
        '/ExpenseControl/11-Cart-page.webm',
        '/ExpenseControl/12-Export-transaction.webm',
      ],
      slug: 'expensecontrol',
    },
    {
      image: "/analytics-dashboard.png",
      tags: ["React", "D3.js", "Express", "AWS"],
      github: "#",
      demo: "#",
      slug: 'stockpro3',
    },
    {
      image: "/social-media-app-feed.jpg",
      tags: ["Next.js", "Supabase", "Tailwind", "Vercel"],
      github: "#",
      demo: "#",
      slug: 'stockpro4',
    },
  ]