export const projects = [
    {
      image: "/Great-stock-pro-image-show3.png",
      tags: ["React.js", "TypeScript", "Node.js", "MongoDB"],
      github: "https://github.com/rodrigojmayer/stockpro",
      demo: 'https://stockpro-deploy.onrender.com/',
      slug: 'stockpro',
      videos: [
        { src: '01-Main-page',
          title: { es: 'Página principal sin inicio de sesión', en: 'Main page unlogged' },
        },
        { src: '02-Sign-up',
          title: { es: 'Página de registro', en: 'Sign up' },
        },
        { src: '03-Log-in-with-user-pass',
          title: { es: 'Iniciar sesión con usuario y contraseña', en: 'Log in with user and password' },
        },
        { src: '04-Log-in-with-gmail',
          title: { es: 'Registro automático e inicio de sesión con Gmail', en: 'Automatic registration and login with Gmail' },
        },
        { src: '05-Create-stock',
          title: { es: 'Crear nuevo stock', en: 'Create new stock' },
        },
        { src: '06-Update-amount',
          title: { es: 'Actualizar cantidad', en: 'Update amount' },
        },
        { src: '07-Edit-stock',
          title: { es: 'Editar stock', en: 'Edit stock' },
        },
        { src: '08-Delete-stock',
          title: { es: 'Eliminar stock', en: 'Delete stock' },
        },
        { src: '09-Massive-update-amount',
          title: { es: 'Actualización masiva de cantidad', en: 'Massive update amount' },
        },
        { src: '10-Alert-by-amount',
          title: { es: 'Alerta por cantidad', en: 'Alert by amount' },
        },
        { src: '11-Alert-by-date',
          title: { es: 'Alerta por fecha', en: 'Alert by date' },
        },
        { src: '12-Alerts-on-top',
          title: { es: 'Alertas en la parte superior', en: 'Alerts on top' },
        },
        { src: '13-Manage-columns',
          title: { es: 'Administrar columnas', en: 'Manage columns' },
        },
        { src: '14-Custom-fields',
          title: { es: 'Campos personalizados', en: 'Custom fields' },
        },
        { src: '15-Order-stock',
          title: { es: 'Ordenar stock', en: 'Order stock' },
        },
        { src: '16-Global-search',
          title: { es: 'Búsqueda global', en: 'Global search' },
        },
        { src: '17-Filter-by-field',
          title: { es: 'Filtrar por campos', en: 'Filter by fields' },
        },
        { src: '18-Profile',
          title: { es: 'Perfil', en: 'Profile' },
        },
        { src: '19-Preferences-language',
          title: { es: 'Lenguajes', en: 'Languages' },
        },
        { src: '20-Preferences-color-mode',
          title: { es: 'Tema visual', en: 'Color mode' },
        },
        { src: '21-Users',
          title: { es: 'Usuarios', en: 'Users' },
        },
        { src: '22-Forgot-password',
          title: { es: 'Olvidé mi contraseña', en: 'Forgot password' },
        },
      ],
    },
    {
      image: "/Great-expensecontrolheroimage.png",
      tags: ["React.js", "TypeScript", "Node.js", "CSS"],
      github: "https://github.com/rodrigojmayer/expense_control_frontend",
      demo: "https://expense-control-frontend.onrender.com/",
      slug: 'expensecontrol',
      videos: [
        { src: '01-Start-page',
          title: { es: 'Pagina de inicio', en: 'Start page' },
        },
        { src: '02-Payment-method-page',
          title: { es: 'Método de pago', en: 'Payment method' },
        },
        { src: '03-Articles-page',
          title: { es: 'Página de artículos', en: 'Articles page' },
        },
        { src: '04-Create-new-article',
          title: { es: 'Crear nuevo artículo', en: 'Create new article' },
        },
        { src: '05-Create-new-group',
          title: { es: 'Crear nuevo grupo', en: 'Create new group' },
        },
        { src: '06-Edit-article',
          title: { es: 'Editar artículo', en: 'Edit article' },
        },
        { src: '07-Delete-article',
          title: { es: 'Eliminar artículo', en: 'Delete article' },
        },
        { src: '08-Edit-group',
          title: { es: 'Editar grupo', en: 'Edit group' },
        },
        { src: '09-Delete-group',
          title: { es: 'Eliminar grupo', en: 'Delete group' },
        },
        { src: '10-Select-articles',
          title: { es: 'Seleccionar artículos', en: 'Select articles' },
        },
        { src: '11-Cart-page',
          title: { es: 'Vista previa del carrito', en: 'Cart preview page' },
        },
        { src: '12-Export-transaction',
          title: { es: 'Exportar transacción', en: 'Export transaction' },
        }
      ],
    },
    {
      image: "/networkimage12.png",
      tags: ["Python", "Django", "Java Script"],
      github: "https://github.com/rodrigojmayer/expense_control_frontend",
      demo: "https://expense-control-frontend.onrender.com/",
      slug: 'network',
      videos: [
        { src: '01-Start-page',
          title: { es: 'Pagina de inicio', en: 'Start page' },
        },
      ],
    },
    {
      image: "/analytics-dashboard.png",
      tags: ["React", "D3.js", "Express", "AWS"],
      github: "#",
      demo: "#",
      slug: 'stockpro3',
    },
    {
      image: "/social-media-app-feed.jpg",
      tags: ["Next.js", "Supabase", "Tailwind", "Vercel"],
      github: "#",
      demo: "#",
      slug: 'stockpro4',
    },
  ]