export const translations = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      projects: "Projects",
      contact: "Contact",
      getInTouch: "Get in Touch",
    },
    hero: {
      name: "Rodrigo Mayer",
      role: "Full-Stack Developer",
      description:
        "Crafting exceptional digital experiences with modern web technologies. Specializing in React, Next.js, and cloud-native solutions.",
      viewWork: "View My Work",
      contactMe: "Contact Me",
    },
    about: {
      title: "About Me",
      subtitle: "Proactive full-stack developer focused on creating scalable, user-centric web applications. Specialized in front-end development with a mobile and responsive approach, with the ability to integrate APIs and work with databases. I excel at applying logic and automation to improve processes and optimize functionality, and I adapt easily to collaborative environments where teamwork is essential.",
      features: {
        cleanCode: {
          title: "Clean Code",
          description: "Writing maintainable, scalable, and performant code following best practices",
        },
        fastDelivery: {
          title: "Fast Delivery",
          description: "Efficient project execution with agile methodologies and modern tooling",
        },
        collaborative: {
          title: "Collaborative",
          description: "Strong communication skills and experience working in cross-functional teams",
        },
      },
      bio1: "I'm passionate about developing well-structured and functional software, and I enjoy learning and experimenting with modern JavaScript frameworks and cloud technologies.",
      bio2: "Outside of my daily work, I dedicate time to exploring new tools, improving my technical skills, and staying up-to-date with industry trends, always with a continuous learning mindset.",
    },
    skills: {
      title: "Skills & Expertise",
      subtitle: "Technologies and tools I work with to bring your ideas to life",
      categories: {
        frontend: "Frontend",
        backend: "Backend",
        devops: "DevOps & Tools",
        services: "Services",
      },
      services: ["Web Programming", "Web Design", "SEO Optimization", "Web Hosting"],
    },
    projects: {
      title: "Featured Projects",
      subtitle: "A selection of my recent work and personal projects",
      code: "Code",
      demo: "Demo",
      close: "Close",
      items: [
        {
          title: "Cuentas Claras",
          description:
            "Digital tool for managing loans and debts with detailed control of financial transactions. It allows users to register loans, manage due dates, view histories by user, and see the status of each debt (active, paid, or overdue). It includes individual profiles, the ability to upload new transactions, data editing, and an authentication system for secure access."
       },
        {
          title: "StockPro",
          description:
            "Web application for managing inventory with advanced stock control features. It allows users to create, update, and organize products, manage quantities individually or in bulk, set alerts by amount or date, and customize views with filters, sorting, and custom fields, along with user access control and multilingual support."
            // "A versatile stock control tool designed for individuals and businesses. It offers customizable features for efficient inventory management, user-specific access levels and multilingual.",
            // "A full-featured e-commerce platform with payment integration, inventory management, and admin dashboard",
        },
        {
          title: "Expenses Control App",
          description: "A billing and sales system designed to centralize corporate revenue by managing customers, payments, and product catalogs. It allows you to organize inventory, manage shopping carts, and automatically calculate totals, completing the cycle with a Google Sheets integration to audit detailed payment history for each customer."
        },
        {
          title: "Network",
          description: "Web site for a Twitter-like social network that allows users to create posts and follow others. Users can browse all posts on the main page, like content, follow profiles, and view personalized feeds such as Following and Liked. The platform also supports editing posts and profile information, including custom profile images or autogenerated avatars.",
        },
        {
          title: "Auction",
          description: 'An eBay-style auction platform where registered users list items by category, place competitive bids, and manage their Watch List. The system allows interaction with the seller through questions, and the seller has full control over closing the listing. It features a design that is 100% responsive on mobile phones and tablets.',
        },
        {
          title: "Mail",
          description: "A single-page internal email application that uses JavaScript and APIs to manage messages without reloading the browser. It allows users to register, compose emails, filter by phrases, and manage inboxes, sent items, and archived messages. It includes features for replying and viewing detailed content, all within a responsive interface.",
        },
        {
          title: "Wiki",
          description: "A collaborative online encyclopedia similar to Wikipedia, fully editable by any user. It offers a comprehensive index of entries, random navigation, and a functional sidebar. Users can easily filter content, create new pages, and edit existing information to keep their shared knowledge base accurate and up-to-date.",
        },
      ],
    },
    contact: {
      title: "Get In Touch",
      subtitle: "Have a project in mind? Let's work together to bring your ideas to life",
      info: {
        email: "Email",
        phone: "Phone",
        location: "Location",
      },
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "your.email@example.com",
        message: "Message",
        messagePlaceholder: "Tell me about your project...",
        send: "Send Message",
        success: "Thank you for your message!",
        error: "An error occurred. Please try again.",
      },
    },
    footer: {
      rights: "All rights reserved.",
      builtWith: "Built with",
      and: "and",
    },
  },
  es: {
    nav: {
      home: "Inicio",
      about: "Acerca de",
      skills: "Habilidades",
      projects: "Proyectos",
      contact: "Contacto",
      getInTouch: "Contáctame",
    },
    hero: {
      name: "Rodrigo Mayer",
      role: "Desarrollador Full-Stack",
      description:
        "Creando experiencias digitales excepcionales con tecnologías web modernas. Especializado en React, Next.js y soluciones nativas en la nube.",
      viewWork: "Ver Mi Trabajo",
      contactMe: "Contáctame",
    },
    about: {
      title: "Acerca de Mí",
      subtitle: "Desarrollador full-stack proactivo enfocado en crear aplicaciones web escalables y centradas en el usuario. Especializado en desarrollo front-end con un enfoque móvil y responsivo, con capacidad para integrar APIs y trabajar con bases de datos. Destaco en la aplicación de lógica y automatización para mejorar procesos y optimizar la funcionalidad, y me adapto fácilmente a entornos colaborativos donde el trabajo en equipo es esencial.",
      features: {
        cleanCode: {
          title: "Código Limpio",
          description: "Escribiendo código mantenible, escalable y eficiente siguiendo las mejores prácticas",
        },
        fastDelivery: {
          title: "Entrega Rápida",
          description: "Ejecución eficiente de proyectos con metodologías ágiles y herramientas modernas",
        },
        collaborative: {
          title: "Colaborativo",
          description: "Fuertes habilidades de comunicación y experiencia trabajando en equipos multifuncionales",
        },
      },
      bio1: "Me interesa el desarrollo de software bien estructurado y funcional, y disfruto aprender y experimentar con frameworks modernos de JavaScript y tecnologías en la nube.",
      bio2: "Fuera del trabajo diario, dedico tiempo a explorar nuevas herramientas, mejorar mis habilidades técnicas y mantenerme actualizado con las tendencias del sector, siempre con una actitud de aprendizaje continuo.",
    },
    skills: {
      title: "Habilidades y Experiencia",
      subtitle: "Tecnologías y herramientas con las que trabajo para dar vida a tus ideas",
      categories: {
        frontend: "Frontend",
        backend: "Backend",
        devops: "DevOps y Herramientas",
        services: "Servicios",
      },
      services: [
        "Programación Web",
        "Diseño Web",
        "Optimización SEO",
        "Alojamiento Web",
      ],
    },
    projects: {
      title: "Proyectos Destacados",
      subtitle: "Una selección de mi trabajo reciente y proyectos personales",
      code: "Código",
      demo: "Demo",
      close: "Cerrar",
      items: [
        {
          title: "Cuentas Claras",
          description: `Herramienta digital para la gestión de préstamos y deudas con control detallado de operaciones financieras. Permite registrar préstamos, administrar vencimientos, consultar historiales por usuario y visualizar el estado de cada deuda (activa, saldada o vencida). Incluye perfiles individuales, carga de nuevas operaciones, edición de datos y sistema de autenticación para un acceso seguro.`,
        },
        {
          title: "StockPro",
          description: `Aplicación web para la gestión de inventario con funciones avanzadas de control de existencias. Permite a los usuarios crear, actualizar y organizar productos, gestionar cantidades de forma individual o masiva, configurar alertas por importe o fecha, y personalizar las vistas con filtros, ordenación y campos personalizados, control de acceso de usuarios y soporte multilingüe.`,
            // "Una plataforma de comercio electrónico completa con integración de pagos, gestión de inventario y panel de administración",
        },
        {
          title: "Expenses Control App",
          description: "Sistema de facturación y ventas diseñado para centralizar los ingresos corporativos mediante la gestión de clientes, cobros y catálogo de productos. Permite organizar inventarios, administrar carritos de venta y calcular totales automáticamente, cerrando el ciclo con una integración en Google Sheets para auditar el historial de cobros detallado por cliente."
        },
        {
          title: "Network",
          description: 'Sitio web para una red social tipo Twitter donde los usuarios pueden crear publicaciones, seguir perfiles y explorar contenido en la página principal. Permite dar "me gusta", ver feeds como "Siguiendo" y "Me gusta", y editar publicaciones e información, incluyendo imágenes o avatares generados automáticamente.',
        },
        {
          title: "Auctions",
          description: "Plataforma de subastas tipo eBay donde usuarios registrados publican artículos por categorías, realizan ofertas competitivas y gestionan su Watch List. El sistema permite interactuar mediante preguntas al vendedor, quien posee control total sobre el cierre del listado. Con un diseño 100% adaptable a móviles y tablets.",
        },
        {
          title: "Mail",
          description: "Single-page application de correo interno que utiliza JavaScript y APIs para gestionar mensajes sin recargar el navegador. Permite registrarse, redactar correos, filtrar por frases y administrar bandejas de entrada, enviados o archivados. Incluye funciones para responder y visualizar contenido detallado, todo bajo una interfaz responsiva.",
        },
        {
          title: "Wiki",
          description: 'Enciclopedia colaborativa en línea similar a Wikipedia, editable por cualquier usuario. Ofrece un índice completo de entradas, navegación aleatoria y una barra lateral funcional. Permite filtrar o buscar contenido, crear nuevas páginas y editar información existente de manera sencilla para mantener el conocimiento siempre actualizado.',
        },
      ],
    },
    contact: {
      title: "Ponte en Contacto",
      subtitle: "¿Tienes un proyecto en mente? Trabajemos juntos para dar vida a tus ideas",
      info: {
        email: "Correo",
        phone: "Teléfono",
        location: "Ubicación",
      },
      form: {
        name: "Nombre",
        namePlaceholder: "Tu nombre",
        email: "Correo",
        emailPlaceholder: "tu.correo@ejemplo.com",
        message: "Mensaje",
        messagePlaceholder: "Cuéntame sobre tu proyecto...",
        send: "Enviar Mensaje",
        success: "¡Gracias por tu mensaje!",
        error: "Ocurrió un error. Intenta de nuevo.",
      },
    },
    footer: {
      rights: "Todos los derechos reservados.",
      builtWith: "Construido con",
      and: "y",
    },
  },
}

export type Language = keyof typeof translations
